### ISSUE TITLE
Alvaro Fidalgo

### ISSUE THREAD

**Issue by Afidalgo-fmm** [Ironhack-Data-Madrid-Octubre-2021/lab-mysql-select#24]
— FIRST QUERIE:

SELECT a.au_id , a.au_lname, a.au_fname , c.title , d.pub_name 
FROM authors AS a, titleauthor AS b, titles AS c, publishers AS d
WHERE a.au_id = b.au_id AND b.title_id = c.title_id AND c.pub_id = d.pub_id;

— SECOND QUERIE:

SELECT a.au_id , a.au_lname, a.au_fname , c.title , d.pub_name 
FROM authors AS a, titleauthor AS b, titles AS c, publishers AS d
WHERE a.au_id = b.au_id AND b.title_id = c.title_id AND c.pub_id = d.pub_id
GROUP BY a.au_id;

— THIRD QUERIE:
SELECT a.au_id , a.au_lname, a.au_fname , c.title , d.pub_name 
FROM authors AS a, titleauthor AS b, titles AS c, publishers AS d
WHERE a.au_id = b.au_id AND b.title_id = c.title_id AND b.title_id = d.title_id
GROUP BY a.au_id
ORDER BY count(title) DESC LIMIT 3;

**Comment by AnaAGG** [comment]
Álvaro, te cierro esta issue que he visto que has hecho también la pull request! 😉
